server:
  port: 8084
  
spring:
  application:
    name: Order-Service
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: Mystrongpass123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
      
eureka:
  instance:
    prefer-ip-address: true
  client: 
    register-with-eureka: true
    fetch-registry: true  
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
          